### ISSUE TITLE
Feature request: Enable the voting/ranking based on a tag

### ISSUE THREAD

**Issue by diego898** [kookma/TW-Vote#2]
Hey Mohammad,

I think it would be great if this plugin could be "enabled" on plugins of a certain tag as opposed to all. 

Thanks!

**Comment by kookma** [comment]
Hi Diego - If I understand you mean instead of having the vote pill on all non-system tiddler one can customize to enable it for certain tags!  

Good idea. I will have a look to add it.

**Comment by kookma** [comment]
This has been addressed in release 1.0.0. Now you can restrict displaying vote pill on certain tiddlers filtered by some criteria!
